# Generated by Django 6.0.5 on 2026-05-30 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebook', '0005_alter_maincategory_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('target_file', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notebook.maincategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notebook.subcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
