# Generated by Django 6.0.5 on 2026-05-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errornote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errornote',
            name='main_category',
        ),
    ]
