# Generated by Django 6.0.5 on 2026-05-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='MainCategory',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='category',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='main_category',
        ),
    ]
