# Generated by Django 6.0.5 on 2026-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_maincategory_name_alter_note_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
