# Generated by Django 6.0.5 on 2026-05-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_note_reference_alter_note_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='command',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.note')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
